name: production Android

on:
  push:
    branches:
      - CI/CD

jobs:
  build:
    environment: Android-Store 
    name: Build and Release AppBundle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Android keystores
        id: android_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: upload-keystore.jks
          encodedString: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      - name: Create key.properties
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: 'gradle'
      - uses: subosito/flutter-action@v2.12.0
        with:
          channel: 'stable'
          version: 3.16.0
          cache: true
      - run: flutter pub get
      - name: build AppBundle with prod env
        run: >
          flutter build appbundle
          --dart-define=isActions=true
          --dart-define=API_BASE=https://socket-server-chat-jhoann-2c28d5d9fb3f.herokuapp.com/api
          --dart-define=API_SOCKETS=https://socket-server-chat-jhoann-2c28d5d9fb3f.herokuapp.com/
          
      - name: Upload Android Release
        uses: actions/upload-artifact@v4
        with:
          name: android-release
          path: build/app/outputs/bundle/release/app-release.aab
  deploy:
    environment: Android-Store 
    name: Deploy Android Build
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Get Android Build from artifacts
      uses: actions/download-artifact@v4
      with:
        name: android-release
    - name: Release Build to internal track
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.JSON_KEY_STORE }}
        packageName: com.jhoann.realTimeChat
        releaseFiles: app-release.aab
        track: qa
        status: completed